In [1]:
#引入tensorflow库
import tensorflow as tf
#构建图
with tf.Graph().as_default() as g:
    tmp = tf.constant(1)#定义0维常量值
    
    for i in range(2,101):
        tmp=tf.add(tmp, i)#节点依赖
#运行会话
with tf.Session(graph=g) as sess:
    print(sess.run(tmp))

D:\Users\lsk\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


5050


In [2]:
import tensorflow as tf
# 构建一个图
g = tf.Graph()
# 将此图作为默认图
with g.as_default():
	op = tf.add(3, 5)
with tf.Session(graph=g) as sess:
    print(sess.run(op))

8


In [3]:
#张量元素运算
import tensorflow as tf
# 创建图
a = tf.add(2,8)#两个数字相加
b = tf.subtract(2,8)#两个数字相减
c = tf.multiply(2,8)#两个数字相乘
d = tf.mod(8,3)#两个数字取模
e = tf.pow(8,2)#幂次方计算
f = tf.square(5)#平方运算
# 创建会话
sess = tf.Session()
# 执行图
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))
print(sess.run(e))
print(sess.run(f))
# 关闭会话
sess.close()

10
-6
16
2
64
25


In [4]:
shape=[2,3]
tf.ones(shape, dtype=tf.float32, name=None)

<tf.Tensor 'ones:0' shape=(2, 3) dtype=float32>

In [5]:
#以三维为例子
#换一下a=28*28个数字就是一样的道理
import tensorflow as tf
#模拟定义三维
a = tf.constant([1,2,3,4,5,6,7,8,9])
#进行转换变形
new_a = tf.reshape(a, [3, 3]) 
#建立会话
with tf.Session() as sess:
    print(sess.run(new_a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#以三维为例子
import tensorflow as tf
input =tf.constant([[[1, 1, 1], [2, 2, 2]],[[3, 3, 3], [4, 4, 4]],[[5, 5, 5], [6, 6, 6]]])
#索引建立
v=tf.slice(input, [1, 0, 0], [1, 1,1]) 
#建立会话
with tf.Session() as sess:
    print(sess.run(v))

[[[3]]]


In [7]:
#使用模拟的全一数据实现shape=[10, 28, 28, 3])
import tensorflow as tf
#创建数据模型
shape=([10, 28, 28, 3])
a = tf.ones(shape)
with tf.Session() as sess:
    print(sess.run(a))
#切片取出第2张图片
v=tf.slice(a, [1, 0, 0,0], [1, 2,28, 3]) 
#建立会话
with tf.Session() as sess:
    print(sess.run(v))

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1

In [8]:
#使用模拟的全一数据实现shape=[10, 28, 28, 3])
import tensorflow as tf
#创建数据模型
shape=([10, 28, 28, 3])
a = tf.ones(shape)
with tf.Session() as sess:
    print(sess.run(a))
#切片取出第1、3、5、7张图片后合并
v1=tf.slice(a, [0, 0, 0,0], [1, 2,28, 3]) 
v3=tf.slice(a, [2, 0, 0,0], [1, 2,28, 3]) 
v5=tf.slice(a, [4, 0, 0,0], [1, 2,28, 3]) 
v7=tf.slice(a, [8, 0, 0,0], [1, 2,28, 3]) 
#合并
v=tf.concat([v1,v3,v5,v7], 0)
#建立会话
with tf.Session() as sess:
    print(sess.run(v))

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1

In [9]:
#使用模拟的全一数据实现shape=[10, 28, 28, 3])
import tensorflow as tf
#创建数据模型
shape=([10, 28, 28, 3])
a = tf.ones(shape)
with tf.Session() as sess:
    print(sess.run(a))
#取出第6,7图片中中心区域（14*14）
v=tf.slice(a, [5, 7, 0,0], [1, 14,14, 3]) 
#建立会话
with tf.Session() as sess:
    print(sess.run(v))

[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1

In [10]:
# 将张量分裂成子张量
split0, split1, split2 = tf.split(a, [1, 1, 1], 3)
m=tf.shape(split0) 
n=tf.shape(split1) 
p=tf.shape(split2) 
#建立会话打印出来
with tf.Session() as sess:
    print(sess.run(m),sess.run(n),sess.run(p))

[10 28 28  1] [10 28 28  1] [10 28 28  1]


In [11]:
a.shape

TensorShape([Dimension(10), Dimension(28), Dimension(28), Dimension(3)])