In [1]:
import tensorflow as tf
const_a=tf.constant([1,2])
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

D:\Users\lsk\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
versions {
  producer: 27
}



In [3]:
import numpy as np

In [13]:
tf.linspace(10.0,13.0,4)

<tf.Tensor 'LinSpace_2:0' shape=(4,) dtype=float32>

In [14]:
a=tf.linspace(10.0,13.0,4)

In [10]:
tf.range(start=3, limit=18, delta=3)

<tf.Tensor 'range:0' shape=(5,) dtype=int32>

In [11]:
tf.range(5)

<tf.Tensor 'range_1:0' shape=(5,) dtype=int32>

In [12]:
with tf.Graph().as_default():
    a = tf.random_uniform([])

    print("Session 1")
    with tf.Session() as sess1:
        print(sess1.run(a))  

    print("Session 2")
    with tf.Session() as sess2:
        print(sess2.run(a))  

Session 1
0.8077904
Session 2
0.660658


In [16]:
with tf.Graph().as_default():
    a = tf.random_uniform([], seed=1)

    with tf.Session() as sess1:
        res1 = sess1.run(a)

    with tf.Session() as sess2:
        res2 = sess2.run(a)
    
    print(res1 == res2)

True


In [17]:
tf.range(start=3, limit=18, delta=3)

<tf.Tensor 'range_2:0' shape=(5,) dtype=int32>

In [20]:
tf.range(2)

<tf.Tensor 'range_3:0' shape=(2,) dtype=int32>

In [21]:
#引入数据库
import tensorflow as tf

In [22]:
#常量存储在图的定义
const_a = tf.constant([1,2])
#返回一个代表当前图的序列化的`GraphDef`
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\001\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "LinSpace/start"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 10.0
      }
    }
  }
}
node {
  name: "LinSpace/stop"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 13.0
      }
    }
  }
}
node {
  name: "LinSpace/num"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr 

In [23]:
tf.linspace(10.0,13.0,5)

<tf.Tensor 'LinSpace_4:0' shape=(5,) dtype=float32>

In [24]:
tf.range(5)

<tf.Tensor 'range_4:0' shape=(5,) dtype=int32>

In [25]:
tf.range(3,18,3)

<tf.Tensor 'range_5:0' shape=(5,) dtype=int32>

In [27]:
tf.random_normal(shape=[1,2],mean=0.0,stddev=1.0,dtype=tf.float32)

<tf.Tensor 'random_normal:0' shape=(1, 2) dtype=float32>

In [28]:
tf.truncated_normal(shape=[1,2],mean=0.0,stddev=1.0,dtype=tf.float32)

<tf.Tensor 'truncated_normal:0' shape=(1, 2) dtype=float32>

In [30]:
tf.random_uniform(shape=[1,2], minval=0, maxval=None, dtype=tf.float32, seed=None,
name=None)

<tf.Tensor 'random_uniform:0' shape=(1, 2) dtype=float32>

In [32]:
tf.random_shuffle(5, seed=None, name=None)

<tf.Tensor 'RandomShuffle:0' shape=() dtype=int32>

In [33]:
#设置了随机数种子时，两个会话中生成的随机数序列是完全一样的
with tf.Graph().as_default():
    a = tf.random_uniform([], seed=1)

    with tf.Session() as sess1:
        res1 = sess1.run(a)

    with tf.Session() as sess2:
        res2 = sess2.run(a)
    
    print(res1 == res2) 


True


In [34]:
# 生成指定shape的全0张量
tf.zeros(shape=[5,8], dtype=tf.float32, name=None)

<tf.Tensor 'zeros:0' shape=(5, 8) dtype=float32>

In [36]:
# 生成与输入的tensor相同shape的全0张量
tf.zeros_like(tf.constant([1,2]), dtype=None, name=None,optimize=True)

<tf.Tensor 'zeros_like:0' shape=(2,) dtype=int32>

In [37]:
# 使用list初始化
var1 = tf.Variable([1, 2, 3])

# 使用ndarray初始化
var2 = tf.Variable(np.array([1, 2, 3]))

# 使用Tensor初始化
var3 = tf.Variable(tf.constant([1, 2, 3]))

# 使用服从正态分布的随机数Tensor初始化
var4 = tf.Variable(tf.random_normal([3, ]))

# 使用变量var1初始化
var5 = tf.Variable(var1)

In [38]:
tf.get_variable(name='get_var', shape=[3, ])

<tf.Variable 'get_var:0' shape=(3,) dtype=float32_ref>

In [42]:
var = tf.Variable([1, 2, 3])
with tf.Session() as sess:
    # 如果没有初始化操作，则抛出异常
    sess.run(var.initializer)
    print(sess.run(var))

[1 2 3]


In [40]:
var1 = tf.Variable([1, 2, 3])
var2 = tf.Variable([1, 2, 3])

with tf.Session() as sess:
    sess.run(tf.variables_initializer([var1, var2]))

In [45]:
var1 = tf.Variable(tf.constant([1,2,3],dtype=tf.float32))

In [46]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [47]:
var1 = tf.Variable([1, 2, 3])
tensor1 = var1.initialized_value()

In [48]:
A = tf.Variable([1, 2, 3])  
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(A))

[1 2 3]


In [50]:
 with tf.Session() as sess:
    sess.run(tf.assign(A, [2, 3, 4]))  
    print(sess.run(A)) 

[2 3 4]


In [51]:
 with tf.Session() as sess:
    sess.run(A.assign([2, 3, 4]))
    print(sess.run(A)) 

[2 3 4]


In [56]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(sess.run(W)) 

10


In [57]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(assign_op)
    print(sess.run(W)) 

100


In [55]:
var = tf.Variable(1)
assign_op = var.assign(2 * var)

with tf.Session() as sess:
    sess.run(var.initializer)
    sess.run(assign_op)
    print(sess.run(var))
    
    sess.run(assign_op)  
    print(sess.run(var))

2
4


In [58]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)

print(sess1.run(W.assign_add(10)))  
print(sess2.run(W.assign_sub(2)))  

sess1.close()
sess2.close()

20
8


In [60]:
a = tf.Variable(1)
b = tf.Variable(a.initialized_value())

with tf.Session() as sess:
    print(sess.run(b.initializer))

None


In [63]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run([W.initializer, assign_op])
    print(sess.run(W)) 

100


In [65]:
W = tf.Variable(10)
with tf.Session() as sess:
    sess.run(W.initializer)
    sess.run(W.assign(100))
    sess.run(W.initializer)
    print(sess.run(W))

10


In [66]:
x = tf.placeholder(dtype=tf.float32, shape=[])
y = tf.placeholder(dtype=tf.float32, shape=[])

z = tf.multiply(x, 2) + y

In [68]:
with tf.Session() as sess:
    print(sess.run(z, feed_dict={x: 5, y: 10}))

20.0


In [87]:
#引入库
import tensorflow as tf
#tf.Variable()初始化
b0 = tf.Variable([1])
b1 = tf.Variable([1])
b2 = tf.Variable([1])
with tf.Session() as sess:
    sess.run(tf.variables_initializer([var1, var2,var3]))
#赋值tf.Variable()
    sess.run(b0.assign([1]))
    sess.run(b1.assign([1]))
    sess.run(b2.assign([1]))
#占位符
x1 = tf.placeholder(dtype=tf.int32, shape=[])
x2 = tf.placeholder(dtype=tf.int32, shape=[])
#构造函数
y = b0 + tf.multiply(x1, b1) +  tf.multiply(x2, b2) 

In [89]:
with tf.Session() as sess:
    print(sess.run(y, feed_dict={x1: [5], x2: [10]}))

ValueError: Cannot feed value of shape (1,) for Tensor 'Placeholder_18:0', which has shape '()'